// src/components/filter-carousel.tsx
'use client'

import { useEffect, useState } from 'react'

import { cn } from '@/lib/utils'
import { Badge } from '@/components/ui/badge'
import {
  Carousel,
  CarouselApi,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from '@/components/ui/carousel'
import { Skeleton } from '@/components/ui/skeleton'

interface Props {
  value?: string | null
  isLoading?: boolean
  onSelect: (value: string | null) => void
  data: {
    value: string
    label: string
  }[]
}

export const FilterCarousel = ({ value, isLoading, onSelect, data }: Props) => {
  const [api, setApi] = useState<CarouselApi>()
  const [current, setCurrent] = useState(0)
  const [count, setCount] = useState(0)

  useEffect(() => {
    if (!api) {
      return
    }
    setCount(api.scrollSnapList().length)
    setCurrent(api.selectedScrollSnap() + 1)

    api.on('select', () => {
      setCurrent(api.selectedScrollSnap() + 1)
    })
  }, [api])

  return (
    <div className="relative w-full">
      <div
        className={cn(
          'pointer-events-none absolute bottom-0 left-12 top-0 z-10 w-12 bg-gradient-to-r from-white to-transparent',
          current === 1 && 'hidden',
        )}
      />
      <Carousel
        setApi={setApi}
        opts={{
          align: 'start',
          dragFree: true,
        }}
        className="w-full px-12"
      >
        <CarouselContent className="-ml-3">
          {!isLoading && (
            <CarouselItem
              onClick={() => onSelect(null)}
              className="basis-auto pl-3"
            >
              <Badge
                variant={!value ? 'default' : 'secondary'}
                className="cursor-pointer whitespace-nowrap rounded-lg px-3 py-1 text-sm"
              >
                All
              </Badge>
            </CarouselItem>
          )}
          {isLoading &&
            Array.from({ length: 14 }).map((_, i) => (
              <CarouselItem key={i} className="basis-auto pl-3">
                <Skeleton className="h-full w-[100px] rounded-lg px-3 py-1 text-sm font-semibold">
                  &nbsp;
                </Skeleton>
              </CarouselItem>
            ))}
          {!isLoading &&
            data.map((item) => (
              <CarouselItem
                key={item.value}
                className="basis-auto pl-3"
                onClick={() => onSelect(item.value)}
              >
                <Badge
                  variant={value === item.value ? 'default' : 'secondary'}
                  className="cursor-pointer whitespace-nowrap rounded-lg px-3 py-1 text-sm"
                >
                  {item.label}
                </Badge>
              </CarouselItem>
            ))}
        </CarouselContent>
        <CarouselPrevious className="left-0 z-20" />
        <CarouselNext className="right-0 z-20" />
      </Carousel>
      <div
        className={cn(
          'pointer-events-none absolute bottom-0 right-12 top-0 z-10 w-12 bg-gradient-to-l from-white to-transparent',
          current === count && 'hidden',
        )}
      />
    </div>
  )
}

// app/components/FilterCarousel.vue
<script setup lang="ts">
import { cn } from "~/lib/utils";
import type { CarouselApi } from "~/components/ui/carousel";

defineProps<{
  isLoading?: boolean;
  data: Array<{
    value: string;
    label: string;
  }>;
  value?: string | null;
}>();
defineEmits<{
  select: [value: string | null];
}>();

const api = ref<CarouselApi>();
const current = ref(0);
const count = ref(0);

function setApi(value: CarouselApi) {
  api.value = value;
}

watchOnce(api, (api) => {
  if (!api) return;

  count.value = api.scrollSnapList().length;
  current.value = api.selectedScrollSnap() + 1;

  api.on("select", () => {
    current.value = api.selectedScrollSnap() + 1;
  });
});
</script>

<template>
  <div class="relative w-full">
    <div
      :class="
        cn(
          'absolute left-12 top-0 bottom-0 w-12 z-10 bg-linear-to-r from-white to-transparent pointer-events-none',
          current === 1 && 'hidden',
        )
      "
    />

    <Carousel
      class="w-full px-12"
      @init-api="setApi"
      :opts="{
        align: 'start',
        dragFree: true,
      }"
    >
      <CarouselContent class="-ml-3">
        <CarouselItem
          v-if="!isLoading"
          @click="() => $emit('select', null)"
          class="pl-3 basis-auto"
        >
          <Badge
            :variant="!value ? 'default' : 'secondary'"
            class="rounded-lg px-3 py-1 cursor-pointer whitespace-nowrap text-sm"
          >
            All
          </Badge>
        </CarouselItem>
        <template v-else>
          <CarouselItem v-for="index in 14" :key="index" class="pl-3 basis-auto">
            <Skeleton class="rounded-lg px-3 py-1 h-full text-sm w-25 font-semibold">
              &nbsp;
            </Skeleton>
          </CarouselItem>
        </template>
        <CarouselItem
          v-for="item in data"
          :key="item.value"
          class="pl-3 basis-auto"
          @click="() => $emit('select', item.value)"
        >
          <Badge
            :variant="value === item.value ? 'default' : 'secondary'"
            class="rounded-lg px-3 py-1 cursor-pointer whitespace-nowrap text-sm"
          >
            {{ item.label }}
          </Badge>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious class="left-0 z-20" />
      <CarouselNext class="right-0 z-20" />
    </Carousel>

    <div
      :class="
        cn(
          'absolute right-12 top-0 bottom-0 w-12 z-10 bg-linear-to-l from-white to-transparent pointer-events-none',
          current === count && 'hidden',
        )
      "
    />
  </div>
</template>
