// app/components/SearchInput.vue
<script setup lang="ts">
import { RiSearchLine } from "@remixicon/vue";
</script>

<template>
  <form class="flex w-full max-w-150">
    <div class="relative w-full">
      <input
        type="text"
        placeholder="Search"
        className="w-full pl-4 py-2 pr-12 rounded-l-full border focus:outline-none focus:border-blue-500"
      />
    </div>
    <button
      type="submit"
      className="px-5 py-2.5 bg-gray-100 border border-l-0 rounded-r-full hover:bg-gray-200 disabled:opacity-50 disabled:cursor-not-allowed"
    >
      <RiSearchLine className="size-5" />
    </button>
  </form>
</template>

// src/modules/studio/ui/components/studio-navbar/search-input.tsx
import { SearchIcon } from 'lucide-react'

export const SearchInput = () => {
  return (
    <form className="flex w-full max-w-[600px]">
      <div className="relative w-full">
        <input
          type="text"
          placeholder="Search..."
          className="w-full rounded-l-full border py-2 pl-4 pr-2 focus:border-blue-500 focus:outline-none"
        />
      </div>
      <button
        type="submit"
        className="rounded-r-full border border-l-0 bg-gray-100 px-5 py-2.5 hover:bg-gray-200 disabled:cursor-not-allowed disabled:opacity-50"
      >
        <SearchIcon className="size-5" />
      </button>
    </form>
  )
}
